drop table paf_batch_loan_master;
create table paf_batch_loan_master(
	tx_brno	varchar(10) comment '交易机构' ,
	plat_date integer comment '平台日期' ,
	plat_time integer comment '平台时间' ,
	plat_trace integer comment '平台流水' ,
	up_brno varchar(10) comment '上级机构' ,
	log_id	varchar(60) comment '日志ID' ,
	log_dev	varchar(20) comment '日志设备' ,
	snd_date varchar(8) comment '发送方日期' ,
	snd_time varchar(6) comment '发送方时间' ,
	snd_seqno varchar(32) comment '发送方流水' ,
	snd_unitno varchar(15) comment '公积金机构号' ,
	snd_node varchar(6) comment '发送方节点号' ,
	rcv_node varchar(6) comment '接收方节点号' ,
	bdc_date varchar(8) comment '结算系统日期' ,
	bdc_time varchar(6) comment '结算系统时间' ,
	bdc_seqno varchar(32) comment '结算系统流水' ,
	cus_no varchar(32) comment '银行客户编号' ,
	opr_no varchar(21) comment '操作员编号' ,
	tx_status varchar(1) comment '交易状态：0、接收；1、登记；2、处理中；3、处理完成；4、转入公积金账户；9、处理失败',
	tx_msg varchar(120) comment '交易处理信息',
	succ_hostseqno varchar(32) comment '成功明细核心系统流水号' ,
	succ_hostrspcode varchar(20) comment '成功明细核心系统响应代码' ,
	succ_hostrspmsg	 varchar(120) comment '成功明细核心系统响应信息' ,
	batch_filename varchar(120) comment '批量文件名',
	batch_no varchar(20) comment '批量编号CRDT开头，贷款是LOAN开头',
	curr_no	 varchar(3) comment '币种，156' ,
	curr_iden	 varchar(1) comment '钞汇鉴别：1、钞；2、汇' ,
	file_type  varchar(1) comment '文件类型：1、同行；2、跨行；3、混合' ,
	batch_prjno  integer comment '批量项目编号' ,
	cr_acctno  varchar(32) comment '收方账号' ,
	cr_acctname  varchar(255) comment '收方户名' ,
	cr_acctclass  varchar(1) comment '收方账户类别：1、对私；2、对公' ,
	bank_accno varchar(32) comment '银行内部过渡户',
	total_num integer comment '总笔数',
	total_amt decimal(16,2) comment '总金额',
	succ_num integer comment '成功总笔数',
	succ_amt decimal(16,2) comment '成功总金额',
	fail_num integer comment '失败总笔数',
	fail_amt decimal(16,2) comment '失败总金额',
	remark varchar(255) comment '备注'
) comment='公积金批量贷款扣款主表' ;
ALTER TABLE paf_batch_loan_master ADD PRIMARY KEY PK_paf_batch_loan_master (plat_date,plat_trace);
CREATE UNIQUE INDEX paf_batch_loan_master_index1 ON paf_batch_loan_master (batch_no) ;
