drop table paf_single_crdt;
create table paf_single_crdt(
	tx_brno	varchar(10) comment '交易机构' ,
	plat_date integer comment '平台日期' ,
	plat_time integer comment '平台时间' ,
	plat_trace integer comment '平台流水' ,
	up_brno varchar(10) comment '上级机构' ,
	log_id	varchar(60) comment '日志ID' ,
	log_dev	varchar(20) comment '日志设备' ,
	snd_date varchar(8) comment '发送方日期' ,
	snd_time varchar(6) comment '发送方时间' ,
	snd_seqno varchar(32) comment '发送方流水' ,
	snd_unitno varchar(15) comment '公积金机构号' ,
	snd_node varchar(6) comment '发送方节点号' ,
	rcv_node varchar(6) comment '接收方节点号' ,
	bdc_date varchar(8) comment '结算系统日期' ,
	bdc_time varchar(6) comment '结算系统时间' ,
	bdc_seqno varchar(32) comment '结算系统流水' ,
	cus_no varchar(32) comment '银行客户编号' ,
	opr_no varchar(21) comment '操作员编号' ,
	tx_status varchar(1) comment '交易状态：0、登记；1、本金记账成功；2、利息记账成功；3、实时交易成功；4、实时部分成功；5、异步受理成功；9、失败' ,
	cap_seqno varchar(32) comment '本金核心系统流水号' ,
	cap_hostcode varchar(20) comment '本金核心系统响应代码' ,
	cap_hostmsg	 varchar(120) comment '本金核心系统响应信息' ,
	int_seqno varchar(32) comment '利息核心系统流水号' ,
	int_hostcode varchar(20) comment '利息核心系统响应代码' ,
	int_hostmsg	 varchar(120) comment '利息核心系统响应信息' ,
	curr_no	 varchar(3) comment '币种，156' ,
	curr_iden	 varchar(1) comment '钞汇鉴别：1、钞；2、汇' ,
	settle_type  varchar(1) comment '结算模式：1、同行；2、跨行实时；3、跨行非实时' ,
	bus_type  varchar(6) comment '业务类型' ,
	de_acctno  varchar(32) comment '付方账号' ,
	de_acctname  varchar(255) comment '付方户名' ,
	de_acctclass  varchar(1) comment '付方账户类别：1、对私；2、对公' ,
	cap_amt  decimal(16,2) comment '本金发生额' ,
	de_intacctno varchar(32) comment '付息户账号 ',
	de_intacctname varchar(255) comment '付息户户名 ',
	de_intacctclass varchar(1) comment '付息户类别:1、对私；2、对公',
	de_intcracct varchar(32) comment '利息收方账号',
	int_amt decimal(16,2) comment '利息发生额',
	cr_acctno varchar(32) comment '收方账号',
	cr_acctname varchar(255) comment '收方户名 ',
	cr_acctclass varchar(1) comment '收方账户类别:1、对私；2、对公',
	cr_bankclass varchar(1) comment '收方账户行别:0、本行；1、跨行',
	cr_bankname varchar(60) comment '收方行名 ',
	cr_chgno varchar(12) comment '收方联行号 ',
	amt  decimal(16,2) comment '交易金额' ,
	ref_acctno varchar(32) comment '业务明细账号', 
	ref_seqno1 varchar(32) comment '业务明细流水号 1',
	ref_seqno2 varchar(32) comment '业务明细流水号 2',
	summary varchar(60) comment '摘要', 
	remark varchar(255) comment '备注'
) comment='公积金单笔付款登记簿' ;
ALTER TABLE paf_single_crdt ADD PRIMARY KEY PK_paf_single_crdt (plat_date,plat_trace);
--CREATE INDEX paf_single_crdt_index1 ON paf_single_crdt (tx_status) ;
--CREATE INDEX paf_single_crdt_index2 ON paf_single_crdt (bdc_date,bdc_seqno) ;