DROP TABLE IF EXISTS paf_acct_mst_report;
CREATE TABLE paf_acct_mst_report (
  id int(11) NOT NULL COMMENT '流水id',
  file_name varchar(100) DEFAULT NULL COMMENT '上送文件名',
  depart_code varchar(5) DEFAULT NULL COMMENT '部门编码',
  center_no varchar(20) DEFAULT NULL COMMENT '公积金中心编号',
  report_time varchar(20) DEFAULT NULL COMMENT '上送时间，格式:YYYYMMDDHHMMSS',
  report_user int(11) DEFAULT NULL COMMENT '上送人',
  num varchar(20) DEFAULT NULL COMMENT '序号',
  acct_no varchar(32) DEFAULT NULL COMMENT '帐号',
  reference varchar(32) DEFAULT NULL COMMENT '银行主机流水号',
  tran_code varchar(6) DEFAULT NULL COMMENT '交易代码',
  oth_acct_no varchar(32) DEFAULT NULL COMMENT '交易对手账号',
  oth_acct_name varchar(255) DEFAULT NULL COMMENT '交易对手户名',
  tran_amt decimal(16,2) DEFAULT NULL COMMENT '金额',
  tran_date varchar(8) DEFAULT NULL COMMENT '交易日期，格式:YYYYMMDD',
  tran_time varchar(6) DEFAULT NULL COMMENT '交易时间，格式:HHMMSS',
  available_amt decimal(16,2) DEFAULT NULL COMMENT '可用金额',
  branch varchar(20) DEFAULT NULL COMMENT '开户机构号',
  remark varchar(255) DEFAULT NULL COMMENT '备注',
  ccy varchar(3) DEFAULT NULL COMMENT '币种，默认156',
  amt_type varchar(1) DEFAULT NULL COMMENT '钞汇标志，1:钞 2:汇',
  balance decimal(16,2) DEFAULT NULL COMMENT '余额',
  odt_balance decimal(16,2) DEFAULT NULL COMMENT '可透支余额',
  doc_type varchar(4) DEFAULT NULL COMMENT '凭证种类',
  voucher_no varchar(16) DEFAULT NULL COMMENT '凭证号码',
  oth_branch varchar(32) DEFAULT NULL COMMENT '交易对手行号',
  narrative varchar(60) DEFAULT NULL COMMENT '摘要',
  reversak varchar(1) DEFAULT NULL COMMENT '冲正标识，Y:冲正，N:未冲正',
  serial_num varchar(50) DEFAULT NULL COMMENT '笔号',
  volume_num varchar(50) DEFAULT NULL COMMENT '册号',
  PRIMARY KEY (id),
  KEY `paf_acct_mst_report_index1` (`file_name`),
  KEY `paf_acct_mst_report_index2` (`report_time`),
  KEY `paf_acct_mst_report_index3` (`acct_no`,`reference`)
) comment '账户变动通知表' ;
